### ISSUE TITLE
Detach Volume (Block Volume) has no way to specify Compartment Id

### ISSUE THREAD

**Issue by avaneesh23** [oracle/oci-java-sdk#107]
DetachVolumeRequest made to ComputeClient returns 404 resource not found because there is no way to specify the Compartment Id.
        *DetachVolumeRequest detachRequest = DetachVolumeRequest.builder().volumeAttachmentId(volumeId).build();*
        *DetachVolumeResponse detachResponse = computeClient.detachVolume(detachRequest);*

There is no DetachVolumeDetails in the API Docs
https://docs.cloud.oracle.com/iaas/tools/java/latest/index.html?com/oracle/bmc/core/responses/DetachVolumeResponse.html

**Comment by jodoglevy** [comment]
Hi,

The [Detach Volume API](https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/Volume/DetachVolume) doesn't take in a compartment id. The reason your example is failing is likely due to the fact that it seems you are passing a `volumeId` in the call, rather than a `volumeAttachmentId`. From your initial comment:
`DetachVolumeRequest.builder().volumeAttachmentId(volumeId).build();`

Can you try passing the volume attachment's id instead?

**Comment by avaneesh23** [comment]
Yes, it works when I pass in the Volume Attachment Id.
I noticed an HTTP GET while accessing the OCI Instance on the Console,
GET /20160918/volumeAttachments/?compartmentId={compartmentId}&volumeId={volumeId}
which got me thinking I needed to pass in compartmentId, volumeId.

Volume Attachment Id is all I need to DetachVolume. Thanks
