### ISSUE TITLE
CreateNodePoolDetails missing nodeImageId field

### ISSUE THREAD

**Issue by biemond** [oracle/oci-java-sdk#125]
Hi,

in src/main/java/com/oracle/bmc/containerengine/model/CreateNodePoolDetails.java builder I am missing the nodeImageId field. 

I think this also recently added to OKE for custom image support and the NodePool class already has this attribute.

thanks

**Comment by jodoglevy** [comment]
Hi @biemond - I don't see a "nodeImageId" field in the [CreateNodePoolDetails API](https://docs.cloud.oracle.com/iaas/api/#/en/containerengine/20180222/datatypes/CreateNodePoolDetails). I do see "nodeImageName", however -- are you sure this isn't the field you are looking for?

**Comment by biemond** [comment]
indeed that is weird I see it on https://docs.cloud.oracle.com/iaas/api/#/en/containerengine/20180222/NodePool/

And I use it on terraform https://www.terraform.io/docs/providers/oci/r/containerengine_node_pool.html#node_image_name

So I think  I use the oci id as value instead on the image name.

**Comment by jodoglevy** [comment]
Let me engage the OKE team on this and see if they have some guidance.

**Comment by alapidas** [comment]
@biemond The API docs are correct here - when creating a node pool, only an image name is used.  When you do a `GET` on a node pool though, the OKE API will return both the image name and ID.  Bear in mind that creating a node pool takes a `CreateNodePoolDetils` resource, not a `NodePool` resource (which is why the object models look different).

With regards to the Terraform link, we will get a ticket open to update the docs there to clarify the expected behavior.

**Comment by biemond** [comment]
thanks again, I will close it.
