### ISSUE TITLE
StreamsExample.java Fails with Error

### ISSUE THREAD

**Issue by chipbaber** [oracle/oci-java-sdk#153]
Hello,
I was attempting to run StreamsExample.java against a clean tenancy. I am able to connect to the service but the sample code fails to create a new instance with the error below. 

[streams_error.txt](https://github.com/oracle/oci-java-sdk/files/3560861/streams_error.txt)

I am able to create a streaming service via the web GUI without error. If I create a service via the console, the script will make it further along, but fails with same error as you try to push a message to stream.

**Comment by andy-miles** [comment]
I have forwarded your issue to the team that owns the sample.

Also, I noticed from your stack trace that you are using the OCI Java SDK with RESTEasy instead of Jersey.  If you want to use RESTEasy, please refer to https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/javasdkconfig.htm and https://github.com/oracle/oci-java-sdk/tree/master/bmc-addons/bmc-resteasy-client-configurator

If you don't want to use RestEasy, insure that you aren't referencing any RESTEasy related jars in your classpath.

**Comment by andy-miles** [comment]
@chipbaber Please let us know if you continue to experience issues running the sample after reviewing my previous comment to address your issue.  If so, please re-open this issue.

**Comment by chipbaber** [comment]
Andy, I can get this to run using the full SDK download and setting the class paths. Which is fine for what I need. The issue appears to be with the .pom file https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/pom.xml. Even if you copy in the bmc-resteasy-client-configurator dependencies to that file, and manually set the sl4j class path and to the .jar for the logging output I still get the same error. Perhaps this is user error on my part, and I need to leverage a different .pom. However the documentation and readme seem to be a little light on the maven side. Seems like it should be pretty straightforward.

**Comment by andy-miles** [comment]
Thanks for the feedback.  I'll look into refactoring the inclusion of the RESTEasy example/dependencies to simply this for others in the future.
