### ISSUE TITLE
Please add an Example for Limits

### ISSUE THREAD

**Issue by loiclefevre** [oracle/oci-java-sdk#198]
The OCI SDK examples are great since they provide working code for a given OCI scope.

However, there is no example to use Limits in the tenant. 

Please provide one for example to get the limit on a given resource for a whole tenant, for a compartment and (if that makes sense) for an Availability Domain.

Thanks

**Comment by loiclefevre** [comment]
Any news on this issue?

**Comment by jodoglevy** [comment]
Hi @loiclefevre  - I will ping the Limits team about this

**Comment by VidhiBhansali** [comment]
Hi @loiclefevre, an example for limits has been added. Please refer [LimitsExample.java](https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/src/main/java/LimitsExample.java)

**Comment by VidhiBhansali** [comment]
Closing this issue since it is fixed and has been open for a while now. Please feel free to reopen it if you have any concern. Thank you!

**Comment by loiclefevre** [comment]
Thanks @VidhiBhansali ! The LimitsExample has however 2 errors: 

LimitsClient client = ...

And in the first service invocation, the .service(SERVICE_NAME) is not useful.

Thanks

**Comment by VidhiBhansali** [comment]
Thanks @loiclefevre. I ran the LimitsExample again to check for the above mentioned errors but was able to run it successfully. I don't think they are actually errors for the reasons below: 

It is ok to define `Limits client = new LimitsClient(provider);` since [LimitsClient.java](https://github.com/oracle/oci-java-sdk/blob/master/bmc-limits/src/main/java/com/oracle/bmc/limits/LimitsClient.java) implements the interface `Limits.java`. 

The `.service(SERVICE_NAME)` in the first service invocation could have been optional but we thought it would be nice to add to show how it could be used. If you try to run the example, you will see that adding SERVICE_NAME will print only the information for that particular service instead of printing them for all.

Please let me know if you still have any questions/concerns.
