### ISSUE TITLE
Building oci-java-sdk-full-1.14.0 jar

### ISSUE THREAD

**Issue by lovababug** [oracle/oci-java-sdk#219]
Hi,

I cloned this repo and checkout to tags/v1.14.0, and below command
`mvn clean install`
 producing **oci-java-sdk-full-1.14.0.jar** of size **2.0K**, but when we download release (from https://github.com/oracle/oci-java-sdk/releases/tag/v1.14.0) it has oci-java-sdk-full-1.14.0.jar of size **25M**. 

Please let me know, if I am missing anything in build command?

**Comment by omkar07** [comment]
Hi @lovababug , Downloaded oci-java-sdk-full-1.14.0.jar from the https://github.com/oracle/oci-java-sdk/releases/tag/v1.14.0 (release zip) is of size 25MB because this jar includes all the modules that Java SDK supports whereas performing mvn clean install on the code checked out from tags/v1.14.0 generates jar files for the individual modules. bmc-full is one such module of Java SDK which will have oci-java-sdk-full-1.14.0.jar of 2KB on executing mvn clean install. Please let us know if this clarifies your doubt.

**Comment by lovababug** [comment]
Thank you @omkar07
