### ISSUE TITLE
API authentication with non-encrypted pvt key and random pass phrase passing

### ISSUE THREAD

**Issue by dipeen-oracle** [oracle/oci-java-sdk#42]
Hi,
I was using API key authentication for login via OCI sdk.
I passed a non-encrypted private key with a random pass phrase to identity service for authentication.
And it passed !!!
Why ?
Don't you use pass phrase key, if private key is not encrypted ?

**Comment by priteshkp** [comment]
Correct, right now there is no validation that if you pass a passphrase, you _must_ provide an encrypted private key.  Only the opposite exists (if you use an encrypted private key, you _must_ provide a passphrase).

Relevant bit of code:
https://github.com/oracle/oci-java-sdk/blob/master/bmc-common/src/main/java/com/oracle/bmc/http/signing/internal/PEMFileRSAPrivateKeySupplier.java#L71

The team can respond with what the behavior should be (I'm just verifying that the current expected behavior is as you describe).

**Comment by mricken** [comment]
The possible change here would be to fail if the provided key is not encrypted and a passphrase was provided.

That may be the correct behavior, but it's not what we have been doing. Starting to do so now could break some clients that rely on being able to set any passphrase for unencrypted keys.

I don't see the benefit in changing this now. If you disagree, please let me know, and I'm happy to reopen this issue for a further discussion.
