### ISSUE TITLE
Rest Post/Put API request failure

### ISSUE THREAD

**Issue by dipeen-oracle** [oracle/oci-java-sdk#48]
Hi,
I'm trying to perform update events like updateImage etc.
Request url: https://iaas.us-phoenix-1.oraclecloud.com/20160918/images/ocid1.image.oc1......
Body:
{
  "displayName": "TestInstanceImage2"
}
Header: Content-Type=application/json
Along with basic auth
I'm getting response:
{
    "code": "NotAuthenticated",
    "message": "The required information to complete authentication was not provided or was incorrect."
}
Please share me what I'm doing wrong here

**Comment by jodoglevy** [comment]
You're receiving an authentication error because OCI does not support basic authentication. You must authenticate via an [API key](https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/signingrequests.htm) or via [instance principals auth](https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Tasks/callingservicesfrominstances.htm).

It looks like you are trying to formulate requests yourself instead of using the SDK methods for the same. Why is that? The SDK has methods for the operations you are trying to call -- for example [UpdateImage](https://docs.us-phoenix-1.oraclecloud.com/tools/java/latest/com/oracle/bmc/core/ComputeClient.html#updateImage-com.oracle.bmc.core.requests.UpdateImageRequest-).

**Comment by dipeen-oracle** [comment]
But If I wanna use a rest client like Postman?
In that case how to fire POST/PUT call?

**Comment by jodoglevy** [comment]
We don't have any easy way for Postman to call OCI APIs at the moment, since Postman does not support our authentication protocol.

However, all of the OCI [SDKs](https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/sdks.htm) support a raw request signer to make arbitrary requests to OCI. In addition, we have 8 signing samples for different languages / tools [here](https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/signingrequests.htm) that can be used to make arbitrary requests to OCI from many different clients (such as Bash). Do any of those options work for your needs?

**Comment by ashishksingh** [comment]
There is an easy way now to use OCI REST APIs with POSTMAN, using steps listed at my blog https://medium.com/@ashi.k.singh/invoking-oci-rest-apis-using-postman-3fda258b0f7a . @dipeen-oracle
