### ISSUE TITLE
Looking for all the IPs within a VCN

### ISSUE THREAD

**Issue by buffaloforge** [oracle/oci-java-sdk#60]
I see where if you have an instanceId within a compartment, that it is easy to obtain the IP address, there is an example of GetInstancePublicIpExample.  However, what if you want to interrogate the entire VCN and pull back all the compute nodes without an instanceId, i have not found within the API where this is possible?

**Comment by nathan-vu** [comment]
Thanks for reaching out and apologies for the delayed response. I've interpreted your question in two ways (but please let me know if I've missed something); unfortunately, for neither of those do I believe there is a single operation you can call to get this information, but you could chain multiple operations together to do so.

> Looking for all the IPs within a VCN

I've interpreted this statement as "find me all the allocated public and private IPs within a VCN". If you want to do this, then you'll need to:

* Call [listSubnets()](https://docs.us-phoenix-1.oraclecloud.com/tools/java/latest/com/oracle/bmc/core/VirtualNetworkClient.html#listSubnets-com.oracle.bmc.core.requests.ListSubnetsRequest-) to get the subnets in the VCN
* Using those subnets, make calls to [listPrivateIps()](https://docs.us-phoenix-1.oraclecloud.com/tools/java/latest/com/oracle/bmc/core/VirtualNetworkClient.html#listPrivateIps-com.oracle.bmc.core.requests.ListPrivateIpsRequest-) and filter by those subnets
  * This will net you a list of `PrivateIp` objects in the response and each of those contains an IP address
* To get public IPs you can call [listPublicIps()](https://docs.us-phoenix-1.oraclecloud.com/tools/java/latest/com/oracle/bmc/core/VirtualNetworkClient.html#listPublicIps-com.oracle.bmc.core.requests.ListPublicIpsRequest-). You'll need to do this multiple times:
  * Once for `RESERVED` public IPs
  * Once for each of your availability domains for `EPHEMERAL` public IPs

---

> what if you want to interrogate the entire VCN and pull back all the compute nodes without an instanceId

I've interpreted this as "show me all instances in a VCN if I only know the VCN OCID". If you want  to do this, you'll need to perform steps along the lines of:

* Do up to (and including) the `listPrivateIps()` part mentioned above. An important piece of information you can pluck out of the `PrivateIp` object is the VNIC OCID. Note that you may get duplicate VNIC OCIDs because of primary and secondary private IPs, so it's best to filter this collection for uniqueness.
* Once you have the VNIC OCID you can use it as a filter in the [listVnicAttachments()](https://docs.us-phoenix-1.oraclecloud.com/tools/java/latest/com/oracle/bmc/core/ComputeClient.html#listVnicAttachments-com.oracle.bmc.core.requests.ListVnicAttachmentsRequest-) operation. The `VnicAttachment` will give you the instance OCID
  * One thing to note here is that it is possible to have an instance and a VNIC reside in separate compartments (but my understanding is that the `VnicAttachment` resides in the same compartment as the instance). If VNICs-and-instances-in-separate-compartments happens in your use case then you would have to make multiple `listVnicAttachment()` calls to cover all your possible compartments.

**Comment by buffaloforge** [comment]
yes, thanks for pointing me in the right direction.
please close this issue out.
