### ISSUE TITLE
ListCompartments does not return root compartment details

### ISSUE THREAD

**Issue by aunayak** [oracle/oci-java-sdk#83]
Hi,
currently List compartment API only returns normal compartment details,
but not root compartment. can we have support for this?

**Comment by MartinSleeman** [comment]
Hey Aunayak,

List compartments, by design gives you the children compartment.  Get compartment will get you the compartment details for any compartment (even the root).   However to get the special Tenancy info you are probably looking for you need Get Tenancy.  https://docs.cloud.oracle.com/iaas/api/#/en/identity/20160918/Tenancy/  that returns the tenancy specific fields.

I hope that answers your question.

**Comment by aunayak** [comment]
Martin,
Thanks for the response.
i just have this concern because the UI and backend will have different behaviours.
ie, in UI if i go Identity -> Compartment , it will list out all the compartments, including child and RootCompartment(Tenancy).
but the same when done from Backend ListCompartment API  the output will be different.
